---
title: "BiobankSplittingResults"
author: "Jennifer Blanc"
date: "2023-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(ggpubr)
library(latex2exp)
```


```{r}
read_in_df <- function(filename, test_num, gwas_num) {
  
  df <- fread(filename)
  df <- df %>% separate(contrast, c("contrast"), ".all")
  df$tp <- test_num
  df$gp <- gwas_num
  
  return(df)
}

df <- read_in_df("../plots/SS/t1000/g50000/results_EA.txt", 1000, 50000)
df <- rbind(df, read_in_df("../plots/SS/t100000/g50000/results_EA.txt", 100000, 50000))
df <- rbind(df, read_in_df("../plots/SS/t5000/g50000/results_EA.txt", 5000, 50000))
df <- rbind(df, read_in_df("../plots/SS/t50000/g50000/results_EA.txt", 50000, 50000))
df <- rbind(df, read_in_df("../plots/SS/t100/g50000/results_EA.txt", 100, 50000))
```

```{r}
# Get bonferonni correction column wise  
df <- df %>% group_by(covar, pc, contrast) %>% mutate(p.adjust = p.adjust(p))
df <- df %>% mutate(sig2 = case_when(p.adjust <= 0.05 ~ "*", p.adjust > 0.05 ~ ""))
df <- df %>% mutate(sig = case_when(p <= 0.05 ~ "*", p > 0.05 ~ ""))

df_North <- df %>% filter(contrast == "north")
df_East <- df %>% filter(contrast == "east")
```

```{r}
df_North$tp <- factor(df_North$tp)
df_North$gp <- factor(df_North$gp)

pl_North <- ggplot(data = df_North, aes( x = gp, y = tp, fill = q)) + geom_tile() + facet_grid(vars(covar), vars(pc)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = TeX("$\\hat{q}$")) + geom_text(aes(label=sig), color="black", size=7, fontface="bold") + theme_bw(base_size = 14) + xlab("") + ylab("Test panel size") + ggtitle("Education Attainment: Test = North")
pl_North
ggsave("~/Desktop/North.png", pl_North)
```

```{r}
df_East$tp <- factor(df_East$tp)
df_East$gp <- factor(df_East$gp)

pl_East <- ggplot(data = df_East, aes( x = gp, y = tp, fill = q)) + geom_tile() + facet_grid(vars(covar), vars(pc)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = TeX("$\\hat{q}$")) + geom_text(aes(label=sig), color="black", size=7, fontface="bold") + theme_bw(base_size = 14) + xlab("") + ylab("Test panel size") + ggtitle("Education Attainment: Test = East")
pl_East
ggsave("~/Desktop/East.png", pl_East)
```

```{r}
df <- fread("../plots/SS/FGrError_NorthEast.txt")
df <- df %>% separate(testSize, into = c("tmp", "testSize"),sep =  "t")
df$testSize <-as.numeric(df$testSize)

ggplot(df, aes(x = testSize, y  = varE, color = contrast))  + geom_point()
```





```{r}
make_plots <- function(filename, test, gwas) {
  
  df <- fread(filename)
  
  title <- paste0("Test Panel: ", test, " ", "GWAS Panel: ", gwas)
  print(title)
  p1 <- ggplot(df, aes(x = PC, y = r2)) + geom_bar(stat = "identity", fill = "aquamarine3") + ylab(TeX("Variance in $\\hat{F}_{Gr}$ Explained")) + xlab("Cumulative PCs") + theme_classic(base_size = 8) + ylim(0,1) + ggtitle(title)

  p2 <-ggplot(df, aes(x = PC, y = rho)) + geom_bar(stat = "identity", fill = "aquamarine4") + geom_errorbar(aes(ymin = lc, ymax = up)) + theme_classic(base_size = 8)+ xlab("PC") + ylab(TeX("$\\rho(PC, \\hat{F}_{Gr})$")) + ylim(-1,1)

  out <- ggarrange(p1,p2)
  return(out)
}

```

```{r}
p1 <- make_plots("../plots/SS/t100/g5000/east_PCs_FGr.txt", 100, 5000)
p2 <- make_plots("../plots/SS/t1000/g5000/east_PCs_FGr.txt", 1000, 5000)
p3 <- make_plots("../plots/SS/t5000/g5000/east_PCs_FGr.txt", 5000, 5000)
p4 <- make_plots("../plots/SS/t50000/g5000/east_PCs_FGr.txt", 50000, 5000)
p5 <- make_plots("../plots/SS/t100000/g5000/east_PCs_FGr.txt", 100000, 5000)

pl_East_small <- ggarrange(p1,p2,p3,p4,p5, nrow = 5)
ggsave("~/Desktop/East_Small.png", pl_East_small, height = 9, width = 7)
```


```{r}
p1 <- make_plots("../plots/SS/t100/g50000/east_PCs_FGr.txt", 100, 50000)
p2 <- make_plots("../plots/SS/t1000/g50000/east_PCs_FGr.txt", 1000, 50000)
p3 <- make_plots("../plots/SS/t5000/g50000/east_PCs_FGr.txt", 5000, 50000)
p4 <- make_plots("../plots/SS/t50000/g50000/east_PCs_FGr.txt", 50000, 50000)
p5 <- make_plots("../plots/SS/t100000/g50000/east_PCs_FGr.txt", 100000, 50000)

pl_East_big <- ggarrange(p1,p2,p3,p4,p5, nrow = 5)
ggsave("~/Desktop/East_Big.png", pl_East_big, height = 9, width = 7)
```


```{r}
p1 <- make_plots("../plots/SS/t100/g5000/north_PCs_FGr.txt", 100, 5000)
p2 <- make_plots("../plots/SS/t1000/g5000/north_PCs_FGr.txt", 1000, 5000)
p3 <- make_plots("../plots/SS/t5000/g5000/north_PCs_FGr.txt", 5000, 5000)
p4 <- make_plots("../plots/SS/t50000/g5000/north_PCs_FGr.txt", 50000, 5000)
p5 <- make_plots("../plots/SS/t100000/g5000/north_PCs_FGr.txt", 100000, 5000)

pl_north_small <- ggarrange(p1,p2,p3,p4,p5, nrow = 5)
ggsave("~/Desktop/north_Small.png", pl_north_small, height = 9, width = 7 )
```
```{r}
p1 <- make_plots("../plots/SS/t100/g50000/north_PCs_FGr.txt", 100, 50000)
p2 <- make_plots("../plots/SS/t1000/g50000/north_PCs_FGr.txt", 1000, 50000)
p3 <- make_plots("../plots/SS/t5000/g50000/north_PCs_FGr.txt", 5000, 50000)
p4 <- make_plots("../plots/SS/t50000/g50000/north_PCs_FGr.txt", 50000, 50000)
p5 <- make_plots("../plots/SS/t100000/g50000/north_PCs_FGr.txt", 100000, 50000)

pl_north_big <- ggarrange(p1,p2,p3,p4,p5, nrow = 5)
ggsave("~/Desktop/north_Big.png", pl_north_big, height = 9, width = 7)
```

```{r}
df5k <- fread("../plots/SS/g5000/pca.eigenval")
df5k$PC <- seq(1,40)

pl <- ggplot(df5k, aes(x=PC, y=V1)) + geom_bar(stat = "identity") + ylab("Eigenvalue") + ggtitle("GWAS = 5,000") + theme_bw()
ggsave("~/Desktop/gwas_small.png", pl)

df50k <- fread("../plots/SS/g50000/pca.eigenval")
df50k$PC <- seq(1,40)

pl <- ggplot(df50k, aes(x=PC, y=V1)) + geom_bar(stat = "identity") + ylab("Eigenvalue") + ggtitle("GWAS = 50,000") + theme_bw()
ggsave("~/Desktop/gwas_big.png", pl)
```

```{r}
df5k <- fread("../plots/SS/g5000/pca.eigenvec")
df50k <- fread("../plots/SS/g50000/pca.eigenvec")

plot(df5k$PC5, df5k$PC6)
plot(df50k$PC1, df50k$PC2)
```


```{r}
df <- fread("~/Downloads/pca.eigenvec")

plot(df$PC9, df$PC10)
```



```{r}
read_in_df <- function(filename, test_num, gwas_num) {
  
  df <- fread(filename)
  colnames(df)[7] <- "contrast"
  colnames(df)[8] <- "pc"
  df$tp <- test_num
  df$gp <- gwas_num
  
  return(df)
}


df <- read_in_df("../plots/SS/eur50000/wbs300000/results_PCs.txt", 50000, 300000)
df <- rbind(df, read_in_df("../plots/SS/eur50000/wbs100000/results_PCs.txt", 50000, 100000))
df <- rbind(df, read_in_df("../plots/SS/eur50000/wbs50000/results_PCs.txt", 50000, 50000))

# Get bonferonni correction column wise  
df <- df %>% group_by(covar, pc, contrast) %>% mutate(p.adjust = p.adjust(p))
df <- df %>% mutate(sig2 = case_when(p.adjust <= 0.05 ~ "*", p.adjust > 0.05 ~ ""))
df <- df %>% mutate(sig = case_when(p <= 0.05 ~ "*", p > 0.05 ~ ""))

df$contrast <- as.factor(df$contrast)
df$pc <- as.factor(df$pc)
df$gp <- as.factor(df$gp)
```


```{r}
pl <- ggplot(data = df, aes(x = gp, y = contrast, fill = q)) + geom_tile() + facet_grid(vars(covar), vars(pc)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = TeX("$\\hat{q}$")) + geom_text(aes(label=sig), color="black", size=7, fontface="bold") + theme_bw(base_size = 14) + xlab("GWAS Panel") + ylab("PC in Test Panel")
ggsave("~/Desktop/pl.png", pl)
```

```{r}
make_plots <- function(filename, test, gwas, name) {
  
  df <- fread(filename)
  
  title <- paste0("Test Vector: ",name, " ", "GWAS Panel: ", gwas)
  print(title)
  p1 <- ggplot(df, aes(x = PC, y = r2)) + geom_bar(stat = "identity", fill = "aquamarine3") + ylab(TeX("Variance in $\\hat{F}_{Gr}$ Explained")) + xlab("Cumulative PCs") + theme_classic(base_size = 8) + ylim(0,1) + ggtitle(title)

  p2 <-ggplot(df, aes(x = PC, y = rho)) + geom_bar(stat = "identity", fill = "aquamarine4") + geom_errorbar(aes(ymin = lc, ymax = up)) + theme_classic(base_size = 8)+ xlab("PC") + ylab(TeX("$\\rho(PC, \\hat{F}_{Gr})$")) + ylim(-1,1)

  out <- ggarrange(p1,p2)
  return(out)
}

```

```{r}
p1 <- make_plots("../plots/SS/eur50000/wbs50000/pc1_PCs_FGr.txt", 50000, 50000, "PC 1")
p2 <- make_plots("../plots/SS/eur50000/wbs50000/pc2_PCs_FGr.txt", 50000, 50000, "PC 2")
p3 <-  make_plots("../plots/SS/eur50000/wbs50000/pc3_PCs_FGr.txt", 50000, 50000, "PC 3")
p4 <-  make_plots("../plots/SS/eur50000/wbs50000/pc10_PCs_FGr.txt", 50000, 50000, "PC 10")
p5 <-  make_plots("../plots/SS/eur50000/wbs50000/pc20_PCs_FGr.txt", 50000, 50000, "PC 20")

pl <- ggarrange(p1,p2,p3,p4,p5, nrow = 5)
ggsave("~/Desktop/PC_50K.png", pl, height = 9, width = 7)
```




## Simulations 

```{r}
df <- fread("../plots/Sims/sim50000/sim300000/results_smooth.txt")
df <- df %>% mutate(sig = case_when(p <= 0.05 ~ "*", p > 0.05 ~ ""))
df$pc <- as.factor(df$pc)
df <- df %>% separate(contrast, c("contrast"), ".all")


ggplot(data = df, aes(x = pc, y = phenotype, fill = q)) + geom_tile() + facet_wrap(~covar) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = TeX("$\\hat{q}$")) + geom_text(aes(label=sig), color="black", size=7, fontface="bold") + theme_bw(base_size = 14)
```














```{r}
df <- fread("../plots/Sims/results.txt")


res <- df %>% group_by(phenotype, covar, contrast, pc, testSize) %>% summarise(count = n(), fp = sum(`p` < 0.05)/ n(), mean_q = mean(q))
res$pc <- as.factor(res$pc)

res_smooth <- res %>% filter(contrast == "smooth")
ggplot(data = res_smooth, aes(x = phenotype, y  = fp, color = pc )) + geom_point() + facet_wrap(~covar)

res_sharp <- res %>% filter(contrast == "sharp")
ggplot(data = res_sharp, aes(x = phenotype, y  = fp, color = pc )) + geom_point() + facet_wrap(~covar)
```


```{r}
Var <-  fread("../plots/Sims/FGrError.txt")
dfVar <- Var %>% group_by(contrast) %>% summarise(meanVar = mean(varE)) 

ggplot(data = dfVar, aes(x = contrast, y = meanVar)) + geom_point()
```

```{r}
df <- fread("../plots/Sims/tp10_50000/gp300000/smooth_PCs_FGr.txt")

ggplot(df, aes(x = PC, y = r2)) + geom_bar(stat = "identity", fill = "aquamarine3") + ylab(TeX("Variance in $\\hat{F}_{Gr}$ Explained")) + xlab("Cumulative PCs") + theme_classic(base_size = 8) + ylim(0,1) 

ggplot(df, aes(x = PC, y = rho)) + geom_bar(stat = "identity", fill = "aquamarine4") + geom_errorbar(aes(ymin = lc, ymax = up)) + theme_classic(base_size = 8)+ xlab("PC") + ylab(TeX("$\\rho(PC, \\hat{F}_{Gr})$")) + ylim(-1,1)
```









```{r}
df  <- fread("../plots/SS/FGrError_WBStest.txt")
df$testSize <- as.numeric(gsub('t', '', df$testSize))

ggplot(data = df, aes(x = testSize, y = varE, color = contrast)) + geom_point()
```



```{r}
df <- fread("../plots/SS/results_WBStest.txt")
df <- df %>% mutate(sig = case_when(p <= 0.05 ~ "*", p > 0.05 ~ ""))
df$pc <- as.factor(df$pc)
df$testSize <- as.factor(df$testSize)
EA <- df %>% filter(phenotype == "Educational_Attainment_6138")
Ht <- df %>% filter(phenotype == "StandingHeight_50")

ggplot(data = Ht, aes(x = pc, y = testSize, fill = q)) + geom_tile() + facet_grid(vars(covar), vars(contrast)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = TeX("$\\hat{q}$")) + geom_text(aes(label=sig), color="black", size=7, fontface="bold") + theme_bw(base_size = 14)

```


```{r}
df <- fread("../plots/AA/resultsEur.txt")
df$exp <- paste0("Test ", df$testSize, " GWAS ", df$gwasSize)
#df2 <- fread("../plots/AA/results2.txt")
#df2$exp <- paste0("Test ", df2$testSize, " GWAS ", df2$gwasSize)
#df <- rbind(df1, df2)
df <- df %>% mutate(sig = case_when(p <= 0.05 ~ "*", p > 0.05 ~ ""))
df$pc <- as.factor(df$pc)
df$testSize <- as.factor(df$testSize)
df_plot <- df %>% filter(rep == "tp4")
#EA <- df %>% filter(phenotype == "Educational_Attainment_6138")
#Ht <- df %>% filter(phenotype == "StandingHeight_50")

ggplot(data = df_plot, aes(x = pc, y = exp, fill = q)) + geom_tile() + facet_grid(vars(covar), vars(contrast)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = TeX("$\\hat{q}$")) + geom_text(aes(label=sig), color="black", size=7, fontface="bold") + theme_bw(base_size = 14) + ylab(" ")

```

```{r}
df <- fread("../plots/AA/tp1_50000/gp60000/north_PCs_FGr.txt")

p1 <- ggplot(df, aes(x = PC, y = r2)) + geom_bar(stat = "identity", fill = "aquamarine3") + ylab(TeX("Variance in $\\hat{F}_{Gr}$ Explained")) + xlab("Cumulative PCs") + theme_classic(base_size = 12) + ylim(0,1) + ggtitle("North")

p2 <- ggplot(df, aes(x = PC, y = rho)) + geom_bar(stat = "identity", fill = "aquamarine4") + geom_errorbar(aes(ymin = lc, ymax = up)) + theme_classic(base_size = 12)+ xlab("PC") + ylab(TeX("$\\rho(PC, \\hat{F}_{Gr})$")) + ylim(-1,1) + ggtitle("North")

out <- ggarrange(p1,p2)
p1
p2
#ggsave("~/Desktop/north.png", out, height = 6, width = 10)
```


